name: Unit-tests

on: [push]

env:
  CARGO_TERM_COLOR:
    always

jobs:
  unit-tests:
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Cache cargo artifacts
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ runner.arch }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Set rust channel
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Clean space
        run: cargo clean --package qvnt-i

      - name: Build crate
        run: cargo build --release --package qvnt-i
        
      - name: Test crate
        run: cargo test --release --package qvnt-i -- -- -q
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
